using System;
using System.Collections.Generic;
using System.Linq;

namespace EvenFibonacciNumbers
{
    // 2. Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    class Program
    {
        const int Limit = 4000000;

        static void Main()
        {
            long evenFinobacciList = 0;

            double totalMiliSeconds = Euler.Common.MeasureTool.MeasureTotalMiliSeconds(() =>
             {
                 evenFinobacciList = Fibonacci(Limit).Where(q => q % 2 == 0).Sum();
             });

            Console.WriteLine("Sum: " + evenFinobacciList + ". Found in " + totalMiliSeconds + " ms");

            Console.Read();
        }

        static IEnumerable<int> Fibonacci(int limit)
        {
            int value1 = 1;
            yield return value1;
            // Console.Write(value1 + ",");
            int value2 = 2;
            yield return value2;
            // Console.Write(value2 + ",");
            int sum = value1 + value2;

            while (sum < limit)
            {
                yield return sum;
                // Console.Write(sum + ",");
                value1 = value2;
                value2 = sum;
                sum = value1 + value2;
            }
        }
    }
}
